rules:
  nesting-depth:
    - 1
    -
      max-depth: 4
  no-misspelled-properties:
    - 1
    -
      'extra-properties':
        - 'composes'
  property-sort-order:
  - 1
  -
    order: 'recess'
    ignore-custom-properties: true